### PR TITLE
Resolve include/exclude issues

### PR DESCRIPTION
**Pull request by zackphilipps**
Possible fix for #20 ?

Also added tests for include/exclude and updated the pluginutils package since it has been moved.

### CODE REVIEW

**Comment by swernerx** [comment]
Great. Thanks. Shoudn't Windows support be checkable by AppVeyor?

**Comment by zackphilipps** [comment]
@swernerx I have no idea. I actually don't think this is a Windows-specific issue, judging by the comments on #20. You're welcome to test this before and after to compare your results. I can definitively say that with my last commit, this works in my project and the 2 Jest tests I added, where it didn't before.

**Comment by zackphilipps** [comment]
@swernerx the key was `filter`ing on `fileSource` instead of `importee`.

**Comment by zackphilipps** [comment]
@swernerx thanks!

**Comment by swernerx** [comment]
Thanks for your help. Indeed it was related to the relative path vs. glob which prefers global paths. This was adjusted in some details by me and is now released as v3.3.0. Can you share whether this version is working correctly for you?

**Pull request merged**
